config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

    resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        post :confirm
      end
    end

    resources :contacts, only: [:new, :create] do
      collection do
        post :confirm
      end
    end

    root 'top#index'

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user && user.admin?
         can :access, :rails_admin
         can :manage, :all
       #else
        # can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true

    belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  PERMISSIBLE_ATTRIBUTES = %i(name)

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:signed_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: [:edit, :update, :destroy]

  def index
      @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end
  end

  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid?
  end

  def create
      @blog = Blog.new(blogs_params)
      @blog.user_id = current_user.id
      if @blog.save
        redirect_to blogs_path, notice: 'ブログを作成しました'
        NoticeMailer.sendmail_blog(@blog).deliver
      else
        render 'new'
      end
  end

  def edit
  end

  def update
      if @blog.update(blogs_params)
        redirect_to blogs_path, notice: 'ブログを編集しました'
      else
        render 'edit'
      end
  end

  def destroy
      @blog.destroy
      redirect_to blogs_path, notice: 'ブログを削除しました'
  end

  private
    def blogs_params
        params.require(:blog).permit(:title, :content)
    end

    def set_blog
        @blog = Blog.find(params[:id])
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
      @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?
  end

  def create
      @contact = Contact.new(contacts_params)
      if @contact.save
        redirect_to new_contact_path,  notice: 'お問い合わせありがとうございました'
      else
         render 'new'
      end
  end

  private
    def contacts_params
        params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new__or_edit
    if action_name == 'mew' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new__or_edit) do |f| %>
    <% if @blog.errors.any? %>
        <div id="error_explanation">
            <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
            <ul>
                <% @blog.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <br>
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control'%>
    <br>
    <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "ブログ一覧画面に戻る", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@blog) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <p>タイトル:<%= @blog.title %></p>
      <p>本文:<%= @blog.content %></p>
      <%= f.submit "登録する", class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "戻る", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ブログ一覧</h1>
      <%= link_to "ブログを作成する", new_blog_path, class: 'btn btn-default' %>
    <% @blogs.each do |blog| %>
    <div class="row">
      <h4><strong><%= blog.title %></strong></h4>
      <p><%= blog.content %></p>
      <%= link_to "ブログを編集する", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "ブログを削除する", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-default btn-sm btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを作成する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
    <% if @contact.errors.any? %>
        <div id="error_explanation">
            <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
            <ul>
                <% @contact.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
    <br>
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
    <br>
    <%= f.submit %>
<% end %>

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>

    <%= form_for(@contact) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>

      <p>名前:<%= @contact.name %></p>
      <p>名前:<%= @contact.email %></p>
      <p>本文:<%= @contact.content %></p>
      <%= f.submit "送信する", class: 'btn btn-primary btn-block' %>
    <% end %>

    <%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>
      <%= f.submit "戻る", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Achieve</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>



  <body>
    <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Achieve", root_path, class: "navbar-brand" %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "お問い合わせ", new_contact_path %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "ブログ", blogs_path %></li>
                        </ul>
                    </li>
                    <% if user_signed_in? %>
                      <li><%= link_to 'マイページ', edit_user_registration_path %></li>
                      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                    <% else %>
                      <li><%= link_to 'ログイン', new_user_session_path %></li>
                      <li><%= link_to 'サインアップ', new_user_registration_path %></li>
                    <% end %>
                </ul>
            </div>
          </div>
        </nav>
    </header>
    <%= yield %>
    <footer>
        <p>株式会社DIVE INTO CODE株式会社</p>
        <p>©️2015-2016Copyright DIVE INTO CODE</p>
    </footer>
  </body>

</html>

app/views/top/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>Achieve</title>
        <link rel="stylesheet" href="normalize.css"/>
        <link rel="stylesheet" href="style.css"/>
        <script src="http://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    </head>
    <body>


        <section class="main-header">
            <p class="flash"><%= notice %><%= alert %></p>
            <img src="<%= asset_path "achieve.png" %>">
        </section>

        <section class="about">
            <h1>About Achive</h1>
        <p>
            Achieveは、受講生のために作成された、教材用アプリです。<br>
            Achieveを作り終えることで、SecondTeamに参加するための力を身に付けることができます。
        </p>
        <p>
            Achieveを一言で表すと、タスク管理アプリです。<br>
            チームメンバーが、今どのようなタスクを行なっているかリアルタイムで把握することができます。
        </p>
        </section>

        <section class="function container-fluid">
            <div class="row">
              <h1>Function</h1>
              <div class="function-images">
                <div class="col-md-3 col-sm-6">
                  <div class="function-image">
                      <img src="<%= asset_path "key.png" %>">
                      <p>ログイン機能</p>
                  </div>
                </div>
                <div class="col-md-3 col-sm-6">
                  <div class="function-image">
                      <img src="<%= asset_path "mails.png" %>">
                      <p>メール送信機能</p>
                  </div>
                </div>
                <div class="col-md-3 col-sm-6">
                  <div class="function-image">
                      <img src="<%= asset_path "girls.png" %>">
                      <p>友達つながり機能</p>
                  </div>
                </div>
                <div class="col-md-3 col-sm-6">
                  <div class="function-image">
                      <img src="<%= asset_path "comment.png" %>">
                      <p>コメント投稿機能</p>
                  </div>
                </div>
              </div>
            </div>
        </section>


        <div id="page-top-btn" class="page-top-btn">
          <p><a id="move-page-top" class="move-page-top">▲</a></p>
        </div>
    </body>
</html>